### ISSUE TITLE
Greedy matching breaks a clue

### ISSUE THREAD

**Issue by TheOriginalSoni** [Jimbly/regex-crossword#21]
For `(...?)\1*` the pattern matching is greedy, which will always accept strings of the form ABCABCABCABC, but fail to match strings like ABABABABABAB

This is because for ? it tries to match maximum number of letters possible (ABA). And then the rest of regex doesn't work anymore. Instead. ? should probably iterate through both options and return True if either is True.

**Comment by Jimbly** [comment]
Thanks, good catch!  I guess in JavaScript we *do* need to prepend/append `^` and `$` to do a full match...
