### ISSUE TITLE
Incorrect clue? [SPOILERS]

### ISSUE THREAD

**Issue by cowboy** [Jimbly/regex-crossword#5]
I just tried this puzzle, and the `.*(.)C\1X\1.*` clue seems to be backwards. I think it should be `.*(.)X\1C\1.*`.

This is as far as I've gotten, but there's no way I can see to reconcile the two red fields.

![](http://i.gyazo.com/33263634b2e95b1b5d071d39e422cc53.png)

If I swap them by setting `board_data.z[8] = '.*(.)X\\1C\\1.*';` I can solve the puzzle:

![](http://i.gyazo.com/4269057b980d40a6d936a71d6daa75dc.png)

**Comment by Jimbly** [comment]
A user reported in #3 that it was transposed, however, *all* of those clues are transposed down there, so I believe the fix was in error.  I have reverted the change, thanks for letting me know =).

**Comment by Jimbly** [comment]
Also, was this puzzle recently linked to or something?  This repository has been idle for 2 years and I just got two issues in a couple days (although, if the first issue caused the second, perhaps that is why =)...

**Comment by cowboy** [comment]
I saw that you closed my other old issue, so I thought I'd try the puzzle again :grin:

**Comment by Jimbly** [comment]
Oh, hah, that explains it then =).
