### ISSUE TITLE
Feature Request: Highlight the 3 affected regexes on hexagon focus

### ISSUE THREAD

**Issue by EhsanKia** [Jimbly/regex-crossword#8]
Pretty self-descriptive request, bold/highlight the three regexes that touch a given cell when the cell is highlighted, tracing it manually by eye can be tricky.

**Comment by offbyone** [comment]
This is off by one (heh) in the top row; you can see my cursor is in the second "column" but it's the first that's being highlighted.

![image](https://user-images.githubusercontent.com/181693/111017951-33479280-836b-11eb-9e79-0005eacfc5e4.png)
